JusticeEngineering/pin-tweet-to-ipfs

src/pages/Background/index.js
=> fix: load oembed tweet instead of whole permalink page

src/background.js
- fixes #8
- use oembed.link for lighter download of web content
=> fix: wait 4 tweet before adding api key

.github/dependabot.yml, .github/workflows/lint.yml
having trouble getting `act` to authenticate correctly in order to run the linter github action locally on my machine (windows woes). Going to see if it 🌟 just works ⭐
=> add lint action and dependabot

README.md
=> Update "available in chrome web store" image

.github/workflows/extension.yml, .gitignore, bundle.sh, package.json
- refs #10
Not closing #10 until I verify that uploads work by pushing new tag
=> Add CI for uploading extension to chrome webstore

.github/workflows/extension.yml
trying to debug why esbuild.js isn't running in the env
=> add debugging ssh to extension action

esbuild.js
- create build dir if doesn't exist
=> fix: extension upload fix

.github/workflows/extension.yml
Reverts meandavejustice/pin-tweet-to-ipfs#27
=> Revert "add debugging ssh to extension action"

.github/workflows/extension.yml, .github/workflows/fetch-access-token.yml
and add action to occasionally refresh access token for chrome webstore
=> switch upload and publish action

package.json
=> Accepting defeat with package version :/

.github/workflows/extension.yml, README.md
- refs #10
Waiting for initial review to be completed before merging
=> feat: add uploads to edge extension store

src/Popup/index.jsx, src/background.js, src/manifest.json
=> feat: add one-click flow for pinning tweet

README.md
-
Closes: # (issue number)
Please attach the screenshots of the changes made in case of change in user interface.
Any other information that is important to this pull request.
=> spacing and grammar change

.github/PULL_REQUEST_TEMPLATE.md, src/manifest.json
#125 included edits to PR template and a grammatical error in manifest.json description, fixed up for merging.
Closes: #111 
=> Fixup #125 for merge

.github/PULL_REQUEST_TEMPLATE.md, src/manifest.json
=> Edited extension name and description

src/content.js
- Selector needed to be updated to match current site html structure
=> Fix content script button in feed

.github/workflows/codeql.yml, .github/workflows/extension.yml, .github/workflows/lint.yml
- update setup-node, checkout, and update-edge
Closes #183, #182, #184 
=> update deps in github actions

package-lock.json, package.json
=> Release 5.0.5

src/content.js
- Duplicate buttons were being added after #193 
- fixes #213 
=> Add check to only add one button to tweet

package-lock.json, package.json
- update packages for 5.0.6 release
=> update packages for 5.0.6 release
